services:
  db:
    image: postgres:latest
    container_name: home-library-db
    environment:
      POSTGRES_DB: home_library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changemeinprod!
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: home-library-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/home_library
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: changemeinprod!

volumes:
  pgdata: